# Generated by Django 3.1 on 2021-07-11 08:51

from django.db import models
from django.db import migrations

import api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vector",
            fields=[
                (
                    "id",
                    api.models.ApiIdField(
                        editable=False, max_length=34, primary_key=True, serialize=False
                    ),
                ),
                ("product_id", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(default=dict)),
                ("title", models.CharField(max_length=32)),
                ("description", models.TextField(blank=True, max_length=512)),
                ("image_url", models.URLField(blank=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
