# Generated by Django 3.1 on 2021-07-22 18:29

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210721_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='doorway',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dpu',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='space',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='RealtimeSpaceData',
            fields=[
                ('id', api.models.ApiIdField(editable=False, max_length=34, primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.space')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', api.models.ApiIdField(editable=False, max_length=34, primary_key=True, serialize=False)),
                ('direction', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('door', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.doorway')),
            ],
        ),
    ]
