# Generated by Django 3.1 on 2021-07-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_auto_20210723_0944"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realtimespacedata",
            name="count",
            field=models.IntegerField(default=0),
        ),
    ]
